site_name: KOMM IN DIE GRUPPE
nav:
  - Home: index.md
theme: material
markdown_extensions:
  - admonition
  - mdx_math
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML